### PR TITLE
fix: typo in aspect-ratio.md filename

### PR DESCRIPTION
**Pull request by OliveLeb**
### Description

Noticed a typo in aspect-ratio.md filename resulting in a type in the route aswell.

### CODE REVIEW

**Comment by productdevbook** [comment]
How can we direct this 302, because I shared it on twitter.

**Comment by OliveLeb** [comment]
We can simply create a middleware, redirecting 301 as it is permanent.
```
export default defineNuxtRouteMiddleware((to, from) => {
  if (to.params.slug.includes('aspet-ratio')) {
    return navigateTo('/docs/primitives/components/aspect-ratio', { redirectCode: 301 })
  }
})
```

something like that

**Comment by OliveLeb** [comment]
Vercel preview did not like it ❌

**Comment by productdevbook** [comment]
When you test it, does it work locally? preview is not 301.

**Comment by OliveLeb** [comment]
Yes, of course

**Comment by productdevbook** [comment]
:(
CleanShot 2023-05-28 at 09 27 12

**Comment by productdevbook** [comment]
fixed: https://github.com/oku-ui/docs/blob/main/nuxt.config.ts#L60-L113

Thanks so much for all your anchors.

**Pull request closed without merging**
